let dataYearly = [
    {
        name:'Free' ,
        paragraph:'Have a go  and test your  superpowers',
        price: 0 ,
        priceBtn: null ,
        title1: '2 Users' ,
        title2: '2 Files' ,
        title3: 'Public Share & Comments' ,
        title4: 'Chat Support ' ,
        title5: 'New income apps' ,
        buttonTitle: 'Signup for free' ,
    } ,
    {
        name:'Pro' ,
        paragraph:'Experiment the power of infinite possibilities',
        price: 8 ,
        priceBtn: 'Save $50 a year' ,
        title1: '4 Users' ,
        title2: 'All apps' ,
        title3: 'Unlimited editable exports' ,
        title4: 'Folders and collaboration ' ,
        title5: 'All incoming apps' ,
        buttonTitle: 'Go to pro' ,
    } ,
    {
        name:'Business' ,
        paragraph:'Unveil new superpowers and join the Design Leaque',
        price: 16 ,
        title1: 'All the features of pro plan' ,
        title2: 'Account success Manager' ,
        title3: 'Single Sign-On (SSO)' ,
        title4: 'Co-conception pogram' ,
        title5: 'Collaboration-Soon' ,
        buttonTitle: 'Goto Business' ,
    } ,
]

let dataMonthly = [
    {
        name:'Free' ,
        paragraph:'Have a go  and test your  superpowers',
        price: 0 ,
        priceBtn: null ,
        title1: '2 Users' ,
        title2: '2 Files' ,
        title3: 'Public Share & Comments' ,
        title4: 'Chat Support ' ,
        title5: 'New income apps' ,
        buttonTitle: 'Signup for free' ,
    } ,
    {
        name:'Pro' ,
        paragraph:'Experiment the power of infinite possibilities',
        price: 4 ,
        priceBtn: 'Save $10 a month' ,
        title1: '4 Users' ,
        title2: 'All apps' ,
        title3: 'Unlimited editable exports' ,
        title4: 'Folders and collaboration ' ,
        title5: 'All incoming apps' ,
        buttonTitle: 'Go to pro' ,
    } ,
    {
        name:'Business' ,
        paragraph:'Unveil new superpowers and join the Design Leaque',
        price: 8 ,
        title1: 'All the features of pro plan' ,
        title2: 'Account success Manager' ,
        title3: 'Single Sign-On (SSO)' ,
        title4: 'Co-conception pogram' ,
        title5: 'Collaboration-Soon' ,
        buttonTitle: 'Goto Business' ,
    } ,
]

export {  dataYearly , dataMonthly }